
server:
  port: 8082

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            user-info-authentication-method: header
        registration:
          internet-banking-core-client:
            provider: keycloak
            client-id: banking-client
            client-secret: rLtwqUNq2yhNIfjDe9H6cuUghA0uTghh
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8181/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        ## USER SERVICE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka


#      security config

app:
  config:
    keycloak:
      url: http://localhost:8181/auth
      realm: banking-service

